stages:
  - build
  - run
  - revert

variables:
  BUILD: "${CI_REGISTRY_IMAGE}:${BRANCH}_${CI_COMMIT_SHA}"
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags: 
    - vadeb11_runner
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      variables:
        BRANCH: "app_prod"
      when: always
    - if: '$CI_COMMIT_REF_NAME == "dev"'
      variables:
        BRANCH: "app_dev"
      when: always
  before_script:
    - echo $BUILD
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache
      --context "${CI_PROJECT_DIR}/django1/"
      --dockerfile "${CI_PROJECT_DIR}/django1/Dockerfile"
      --destination "${BUILD}"

run:
  stage: run
  image: 
    name: docker:dind
  tags:
    - vadeb11_runner
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      variables:
        BRANCH: "app_prod"
        PORT: '8000'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "dev"'
      variables:
        BRANCH: "app_dev"
        PORT: '8001'
      when: always
  variables:
    BUILD: "${CI_REGISTRY_IMAGE}:${BRANCH}_${CI_COMMIT_SHA}"
  before_script:
    - echo $BUILD
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose up -d

revert:
  stage: revert
  tags: 
    - vadeb11_runner
  variables:
    BUILD: "${CI_REGISTRY_IMAGE}:${BRANCH}_${CI_COMMIT_BEFORE_SHA}"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      variables:
        BRANCH: "app_prod"
        PORT: '8000'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "dev"'
      variables:
        BRANCH: "app_dev"
        PORT: '8001'
      when: manual
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose up -d
