image: docker:dind
services:
  - docker:dind

stages:
  - build

build_prod:
  stage: build
  tags: 
    - vadeb11_runner
  variables:
    PROD: "prod"
    BUILD: "$CI_REGISTRY_IMAGE:app_prod_$CI_COMMIT_SHORT_SHA"
    PORT: '8000'
  before_script:
    - echo $BUILD
    - echo $CI_REGISTRY
    - docker login -u $USER -p $TOKEN $CI_REGISTRY
  script:
    - cd django1/
    - docker build -t $BUILD .
    - docker push $BUILD
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always

        #build_dev:
        #  stage: build
        #  tags:
        #   - vadeb11_runner
        #  variables:
        #    DEV: "dev"
        #    PORT: '8001'
        #  script:
        #  - docker-compose up -d
