

stages:
  - build
variables:
  PROD: "app_prod"
  DEV: "app_dev"
build_prod:
  stage: build
  tags: 
    - vadeb11_runner
  variables:
    #   PROD: "app_prod"
    BUILD: "$CI_REGISTRY_IMAGE:$PROD_$CI_COMMIT_SHORT_SHA"
    PORT: '8000'
  before_script:
    - echo $BUILD
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - cd django1/
    - docker build -t $BUILD .
    - docker push $BUILD
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always

build_dev:
  stage: build
  tags:
    - vadeb11_runner
  variables:
    #  DEV: "app_dev"
    PORT: '8001'
  script:
    - docker-compose up -d
